---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  name: blog-1
spec:
  chart_name: blog-1
  release: blog-1
  namespace: default
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values: {}
  source:
    type: tar
    location: https://TO_REPLACE/artifactory/helm-charts/openstack-helm-infra/memcached-ff84ab86dcb1.ff84ab86dcb1.tgz
    subpath: memcached
  dependencies: []
