---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  labels:
    component: mariadb
    name: mariadb
  name: mariadb
spec:
  chart_name: mariadb
  dependencies:
  - helm-toolkit
  release: mariadb
  source:
    location: https://opendev.org/openstack/openstack-helm-infra
    reference: f0306ce33de4821689b38893d03aabf30f5f6092
    subpath: mariadb
    type: git
  target_state: deployed
  upgrade:
    no_hooks: false
    pre:
      delete:
      - labels:
          release_group: mariadb
        type: job
  values:
    endpoints:
      oslo_db:
        auth:
          admin:
            password: airsloop123
            username: root
          exporter:
            password: airsloop123
        host_fqdn_override:
          default: ""
        hosts:
          default: mariadb
          discovery: mariadb-discovery
        path: /DB_NAME
        port:
          mysql:
            default: 3306
          wsrep:
            default: 4567
        scheme: mysql+pymysql
      prometheus_mysql_exporter:
        auth:
          user:
            username: osh-oslodb-exporter
        host_fqdn_override:
          default: ""
        hosts:
          default: mysql-exporter
        path:
          default: /metrics
        port:
          metrics:
            default: 9104
        scheme:
          default: http
    images:
      tags: {}
    labels:
      prometheus_mysql_exporter:
        node_selector_key: control-plane
        node_selector_value: enabled
      server:
        node_selector_key: control-plane
        node_selector_value: enabled
    monitoring:
      prometheus:
        enabled: true
    pod:
      replicas:
        ingress: 1
        server: 1
  wait:
    labels:
      release_group: mariadb
    timeout: 900
---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  labels:
    component: memcached
    name: memcached
  name: memcached
spec:
  chart_name: memcached
  dependencies:
  - helm-toolkit
  release: memcached
  source:
    location: https://opendev.org/openstack/openstack-helm-infra
    reference: f0306ce33de4821689b38893d03aabf30f5f6092
    subpath: memcached
    type: git
  target_state: deployed
  upgrade:
    no_hooks: false
    pre:
      delete:
      - labels:
          release_group: memcached
        type: job
  values:
    endpoints:
      oslo_cache:
        host_fqdn_override:
          default: ""
        hosts:
          default: memcached
        port:
          memcache:
            default: 11211
    images:
      tags: {}
    labels:
      server:
        node_selector_key: control-plane
        node_selector_value: enabled
  wait:
    labels:
      release_group: memcached
    timeout: 900
---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChart
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq
spec:
  chart_name: rabbitmq
  dependencies:
  - helm-toolkit
  release: rabbitmq
  source:
    location: https://opendev.org/openstack/openstack-helm-infra
    reference: f0306ce33de4821689b38893d03aabf30f5f6092
    subpath: rabbitmq
    type: git
  target_state: deployed
  upgrade:
    no_hooks: false
    pre:
      delete:
      - labels:
          release_group: rabbitmq
        type: job
  values:
    endpoints:
      oslo_messaging:
        auth:
          user:
            password: password123
            username: admin
        host_fqdn_override:
          default: ""
        hosts:
          default: rabbitmq
        path: /VHOST_NAME
        port:
          amqp:
            default: 5672
          http:
            default: 15672
        scheme: rabbit
        statefulset:
          name: rabbitmq-rabbitmq
      prometheus_rabbitmq_exporter:
        host_fqdn_override:
          default: ""
        hosts:
          default: rabbitmq-exporter
        path:
          default: /metrics
        port:
          metrics:
            default: 9095
        scheme:
          default: http
    images:
      tags: {}
    labels:
      prometheus_rabbitmq_exporter:
        node_selector_key: control-plane
        node_selector_value: enabled
      server:
        node_selector_key: control-plane
        node_selector_value: enabled
    monitoring:
      prometheus:
        enabled: true
    pod:
      replicas:
        server: 1
  wait:
    labels:
      release_group: rabbitmq
    resources:
    - type: statefulset
    timeout: 900
