---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: armada-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: armada-operator
  template:
    metadata:
      labels:
        name: armada-operator
    spec:
      serviceAccountName: armada-operator
      containers:
        - name: armada-operator
          image: keleustes/armada-operator-dev:v2.14.1
          command:
          - armada-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "armada-operator"
